![Wolfe](https://s3.amazonaws.com/lquant-images/wolfe_luo.jpg)

# Overview of Python Risk Model API
**pyqes.micsvc**:

Python package to utilize the Luo QES API service functions. The API can be used to build historical risk models. It provides a convenient way to build a risk model using standard or customized universes. User can select 

1. Risk Universe
2. List of factors
3. Parameters for estimation

The risk model parameters are driven from risk model templates. We provide standard risk model templates that can be copied/edited/saved as user specific templates.

## Requirements and Presteps

1. Copy pyqes [python file]( https://github.com/wolferesearch/docs/tree/master/micro-services/api/python/pyqes) from github to your local directory from Github. 
2. Ensure you have [Pandas](https://pandas.pydata.org/) and [requests](https://pypi.org/project/requests/) package in your python kernel.

## Authentication and Connection

The API is protected using Username and Password. In case you have not received it, please [email](mailto:luo.qes@wolferesearch.com) to apply for API account. 

The connection object is the gateway to accessing the API. It allows you to access the catalog, portfolios, templates, risk models etc.

In [1]:
# The micsvc folder should be in your working directory
from pyqes import micsvc

user = '********'
# create a connection object to interact with the server
connection = micsvc.Connection(username = user, password = '*******')

### Connection Class

Provides convenients way to interface with the Cataglog/Risk/Template RESTful API. The first step is to browse the catalog that provides access to Universes and Factors.

In [2]:
# Catalog instance allows you browse different entities in the database...
catalog = connection.get_catalog()

### Catalog

* <ins>**Universe**</ins> : Time varying collection of stocks. We have wide array of universe available. Additional universes can be added to the collection on client's request. 


* <ins>**Factor**</ins>: List of available factors (or features, e.g., Earnings Yield, ROE, ..) for stocks. The factors form the basis for risk model and capturing the systematic risk. The factors can be added to the risk model template to enhance the model. While adding more factor can better capture the systematic risk, caution should be exercised in order to avoid overfitting. Also, it is advisable to add correlated factors as they can cause multi-collinearity. 


* <ins>**Meta Factor**</ins>: List of meta data available (e.g., Market Cap, Ticker, ..) for stocks. This is for reference and mapping purpose. 


* <ins>**Portfolio**</ins>: User can upload portfolio to the database. Portfolios are saved in users own space. The purpose of the portfolio is to be used as a custom universe for risk model and other requests. 


* <ins>**Template**</ins>: A template is stored parameter set for the risk model requests. The two main purposes of templates are (1) Simplifying the API, and (2) Reuse parameters across different requests.

### Factors

We have a wide array of factors available capturing fundamental and technical themes of the stocks. The factors are based on years of extensive alpha/risk research by the QES team. The catolog provides an easy way to list down available factors. In case you are interested in additional factors, please [email](mailto:luo.qes@wolferesearch.com) desk.

In [3]:
catalog.get_factors().head()

,CATEGORY,DESCRIPTION,ID,SUBCATEGORY
0,Value,"Book-to-market, FY1",BOOKP_FY1,Book
1,Value,"Price-to-EPS, LTM, diluted",PE_LTM_D,Earnings
2,Value,"Operating cash flow yield, FY1 (= Last 12 mont...",CFOYLD_FY1,Cash flow
3,Value,"Earnings yield (LTM, basic) x 5Y Exp Growth",EPSYLD_GRO,GARP
4,Value,"Earnings yield, LTM, operating",EPSYLD_LTM_O,Earnings

### Universe

Collection of standardized universe that can be used as risk universe. Note that custom portfolios can also be used as risk universe. The ID colun in the table below uniquely identifies the universe.

In [4]:
catalog.get_universe().head()

,COUNTRY,DESCRIPTION,ID,NAME,SECTOR
0,US,Universe stocks from US based on Market Capita...,US_1,US Broad Market Index,All
1,US,Universe provides constituents for S&P 500,SP500,QES 500,All
2,US,Universe provides constituents for S&P 1500,SP1500,QES 1500,All
3,US,Russell 2000 Index,CIQ_INDEX_2667223,Russell 2000 Index,All
4,US,Russell 1000 Index,CIQ_INDEX_2668794,Russell 1000 Index,All

### Portfolio

Similar to universe but user can upload it along with custom factors. A single portfolio added to the database can provide a risk universe as well as custom factors. Note that any columns other than date/id are treated as custom factors). For more details on format of the CSV file, please see our [Github link](https://github.com/wolferesearch/docs/blob/master/portfolio.md). You can also download a sample file using this [link](https://raw.githubusercontent.com/wolferesearch/docs/master/sample/LongFormatPort.csv).

In [5]:
catalog.get_portfolios()

                            ID UPLOADEDBY              UPLOADEDTIME
0  CENTIVA_MY_CUSTOM_PORTFOLIO    centiva  2023-01-10T00:00:00.000Z

### Uploading a portfolio

A simple CSV file can be uploaded a custom list. We support Ticker (US Only), SEDOL, CUSIP, BBTICKER as valid identifiers.

In [6]:
# Always prefix the user with the username to avoid conflict

# You can also download a sample file using this https://raw.githubusercontent.com/wolferesearch/docs/master/sample/LongFormatPort.csv
portfolio_id = '{}_MY_CUSTOM_PORTFOLIO'.format(user.upper())
portfolio = connection.upload_portfolio(id = portfolio_id, filename = '../../../sample/LongFormatPort.csv')

In [7]:
# Check if the 
portfolio.text

'file uploaded successfully'

In [8]:
catalog.get_portfolios()

                            ID UPLOADEDBY              UPLOADEDTIME
0  CENTIVA_MY_CUSTOM_PORTFOLIO    centiva  2023-01-10T00:00:00.000Z

<span style="color:red">*Note that a portfolio to be used a risk model universe, it is important to have wide and deep coverage. The example above is a very simple portfolio. It is recommended to provide portfolio with at least one month frequency* and have at least 10-20 stocks in each of the GICS industry group</span>

### Templates

Templates are stored parameters that can be reused. Templates are stored as Json file in the database. Users can take an existing template and modify it and save it back in the database. The template will be stored under individual users space and only visible to the account you are using to connect.

In [9]:
## Get all templates using the catalog class
catalog.get_templates()

,CONTENT,DESCRIPTION,MODIFIED_DATE,NAME,OWNER,TYPE
0,"{'meta': [{'mnemonic': 'SEDOL', 'name': 'Sedol...",Model uses default set of factors and grouping...,2019-01-18T16:34:39.000000,default,admin,Risk-Model
1,"{'meta': [{'mnemonic': 'SEDOL', 'name': 'Sedol...",Model is build for Euro with default currency ...,2023-01-04T15:42:10.000000,default-euro,admin,Risk-Model
2,"{'meta': [{'mnemonic': 'TICKER', 'name': 'Tick...",TMT Default Model,2019-03-22T18:10:49.000000,custom-tmt,admin,Risk-Model
3,"{'loadAxiomaIdioRisk': 'true', 'runWithDailyPe...",Default Attribution Template,2019-04-11T18:02:33.000000,default,admin,Optimization
4,"{'meta': [{'mnemonic': 'TICKER', 'name': 'Tick...",Energy Risk Model,2019-07-19T17:31:48.000000,us-energy,admin,Risk-Model
5,"{'min_long_weight': 1, 'use_benchmark': False,...",Model uses default optimization,2022-06-20T04:21:46.000000,default,admin,Optimization
6,"{'min_long_weight': 1, 'use_benchmark': False,...",Model uses default optimization,2021-06-16T19:38:42.000000,mvo-example,admin,Optimization
7,"{'expression': 'rule0 & rule1 & !rule3', 'freq...",US-1 Estimation Universe for feeding Risk Model,2019-09-06T15:28:32.000000,us-1,admin,Optimization
8,"{'rules': [{'type': 'conditions', 'bool': 'and...",US-1 Estimation Universe for feeding Risk Mode...,2019-09-05T21:05:36.000000,us-1-m,admin,Optimization
9,"{'meta': [{'mnemonic': 'SEDOL', 'name': 'Sedol...",centiva_risk_with_cash_flow,2023-01-10T17:09:37.000000,centiva_risk_with_cash_flow,centiva,Risk-Model

In [10]:
default_risk_template = connection.get_template(name = 'default', type_ = 'Risk-Model')

### Inspecting the Template

In [11]:
default_risk_template.json

{'__name__': 'default',
 '__type__': 'ltool.risk.RiskModelBuilder',
 'covArgs': {'cov.period': 252,
  'expWeight': 'true',
  'interval': 3,
  'var.period': 84},
 'factors': [{'mnemonic': 'EPSYLD_LTM_B', 'name': 'Earnings Yld'},
  {'mnemonic': 'GR_INTR_EPS', 'name': 'EPS Growth (YoY)'},
  {'mnemonic': 'RTN_12M1M', 'name': 'Momentum (12M-1M)'},
  {'mnemonic': 'ES_EPS_NTM_R3M', 'name': 'Revision'},
  {'mnemonic': 'ROE', 'name': 'Profitability'},
  {'mnemonic': 'REAL_VOL', 'name': 'Volatility'},
  {'mnemonic': 'MKTCAP_M_USD', 'name': 'Size (Mkt. Cap)'},
  {'mnemonic': 'DIVYLD_TRL', 'name': 'Div Yield'},
  {'mnemonic': 'BOOKP', 'name': 'Book to Market'}],
 'meta': [{'mnemonic': 'SEDOL', 'name': 'Sedol'},
  {'mnemonic': 'TICKER', 'name': 'Ticker'},
  {'mnemonic': 'COMPANYNAME', 'name': 'Company Name'},
  {'mnemonic': 'QES_GSECTOR', 'name': 'Sector'},
  {'mnemonic': 'QES_GGROUP', 'name': 'Industry Group'},
  {'mnemonic': 'QES_COUNTRY', 'name': 'Country'},
  {'mnemonic': 'CURRENCY', 'name': 'Currency'}],
 'options': {'spRisk': {'fn': 'median', 'shrinkage': 0.5}}}

#### Adding a new factor to the template

In [12]:
## Add a new Factor to the template
default_risk_template.add_factor(mnemonic = 'CFOYLD_FY1', name = 'Cash Flow Yield')

#### Saving template to the database

In [13]:
## Save the template to the database. Please use 
template_name = '{}_risk_with_cash_flow'.format(user)
default_risk_template.save(template_name)

#### Ensuring the new template has the new factor we added

In [14]:
## Get Template
risk_template = connection.get_template(name = template_name, type_ = 'Risk-Model')
risk_template.json

{'__name__': 'centiva_risk_with_cash_flow',
 '__type__': 'ltool.risk.RiskModelBuilder',
 'covArgs': {'cov.period': 252,
  'expWeight': 'true',
  'interval': 3,
  'var.period': 84},
 'factors': [{'mnemonic': 'EPSYLD_LTM_B', 'name': 'Earnings Yld'},
  {'mnemonic': 'GR_INTR_EPS', 'name': 'EPS Growth (YoY)'},
  {'mnemonic': 'RTN_12M1M', 'name': 'Momentum (12M-1M)'},
  {'mnemonic': 'ES_EPS_NTM_R3M', 'name': 'Revision'},
  {'mnemonic': 'ROE', 'name': 'Profitability'},
  {'mnemonic': 'REAL_VOL', 'name': 'Volatility'},
  {'mnemonic': 'MKTCAP_M_USD', 'name': 'Size (Mkt. Cap)'},
  {'mnemonic': 'DIVYLD_TRL', 'name': 'Div Yield'},
  {'mnemonic': 'BOOKP', 'name': 'Book to Market'},
  {'mnemonic': 'CFOYLD_FY1', 'name': 'Cash Flow Yield'}],
 'meta': [{'mnemonic': 'SEDOL', 'name': 'Sedol'},
  {'mnemonic': 'TICKER', 'name': 'Ticker'},
  {'mnemonic': 'COMPANYNAME', 'name': 'Company Name'},
  {'mnemonic': 'QES_GSECTOR', 'name': 'Sector'},
  {'mnemonic': 'QES_GGROUP', 'name': 'Industry Group'},
  {'mnemonic': 'QES_COUNTRY', 'name': 'Country'},
  {'mnemonic': 'CURRENCY', 'name': 'Currency'}],
 'name': 'centiva_risk_with_cash_flow',
 'options': {'spRisk': {'fn': 'median', 'shrinkage': 0.5}}}

## Risk Model Builder

Risk Model Builder requires the following parameters to build the risk model

1. Universe: This can be one of the standard universes or custom portfolio ids
2. Template: Template containing the parameters such as factor lists, meta data list, and other parameters
3. Start Date: First date when the risk model should be built
4. End Date: Last date 
5. Frequency: How often to rebuild between the start and end date. Available frequencies are 
   1. Daily :  1d
   2. N Daily: nd
   3. Weekly: 1w
   4. Monthly: 1m
   5. Month End: 1me
   6. Quarterly: 1q
   7. Quarter End: 1qe
   8. Yearly: 1y
   9. Year End: 1ye

In [15]:
# Get a new Risk model builder
rmb = connection.get_risk_model_builder()
rmb.new_request(universe = 'SP500', template = template_name, startDate = '2020-01-31', endDate = '2022-12-31', freq = '1me')

In [56]:
## Wait until the risk model is completed. 
rmb.wait(max_wait_secs = 600)

{'dates': ['2020-01-31',
  '2020-02-29',
  '2020-03-31',
  '2020-04-30',
  '2020-05-31',
  '2020-06-30',
  '2020-07-31',
  '2020-08-31',
  '2020-09-30',
  '2020-10-31',
  '2020-11-30',
  '2020-12-31',
  '2021-01-31',
  '2021-02-28',
  '2021-03-31',
  '2021-04-30',
  '2021-05-31',
  '2021-06-30',
  '2021-07-31',
  '2021-08-31',
  '2021-09-30',
  '2021-10-31',
  '2021-11-30',
  '2021-12-31',
  '2022-01-31',
  '2022-02-28',
  '2022-03-31',
  '2022-04-30',
  '2022-05-31',
  '2022-06-30',
  '2022-07-31',
  '2022-08-31',
  '2022-09-30',
  '2022-10-31',
  '2022-11-30',
  '2022-12-31'],
 'endTime': '"2023-01-10 17:23:19.057875"',
 'message': 'Job Completed ',
 'startTime': '"2023-01-10 17:22:34.642081"',
 'status': 'SUCCESS',
 'uuid': 'fe0b2d15-5ca4-4f8a-99a0-06dcb5362cde'}

In [49]:
# Print out dates of the risk model that was just built
rmb.dates()

['2020-01-31',
 '2020-02-29',
 '2020-03-31',
 '2020-04-30',
 '2020-05-31',
 '2020-06-30',
 '2020-07-31',
 '2020-08-31',
 '2020-09-30',
 '2020-10-31',
 '2020-11-30',
 '2020-12-31',
 '2021-01-31',
 '2021-02-28',
 '2021-03-31',
 '2021-04-30',
 '2021-05-31',
 '2021-06-30',
 '2021-07-31',
 '2021-08-31',
 '2021-09-30',
 '2021-10-31',
 '2021-11-30',
 '2021-12-31',
 '2022-01-31',
 '2022-02-28',
 '2022-03-31',
 '2022-04-30',
 '2022-05-31',
 '2022-06-30',
 '2022-07-31',
 '2022-08-31',
 '2022-09-30',
 '2022-10-31',
 '2022-11-30',
 '2022-12-31']

### Getting the data the request. 

Risk model data can be easily accessed by query it one date at a time. The data is returned as a dictionary containing data for one day:

1. Security Exposures (*.exp)
2. Security Master (*.idm)
3. Factor Returns (over the period) (*.rtn)
4. Security Specific Risk (*.rsk)
5. Factor Mimicking Portfolio (*.fmp)
6. Security Meta (*.meta)
7. Factor Info file (*.info)



<span style="color:red">*Note that data for each risk model request is kept in the database based on UID of the request. The UID can be retrieved using the connection.jobs() function of a previous request. You can always query an old request by associating the builder with previous run UID</span>

In [20]:
data = rmb.get_data('2022-12-31')

In [41]:
## Unique Id That can be either saved by the client or it can be queries by using the connection.get_jobs()
rmb.esvc.get_id

'fe0b2d15-5ca4-4f8a-99a0-06dcb5362cde'

In [42]:
connection.get_jobs()

,ENDTIME,MESSAGE,STARTTIME,STATUS,TYPEID,USER_,UUID
0,1673303489333,Job Completed,2023-01-09 22:30:59.822,SUCCESS,1,centiva,f8a4911d-8bdb-427f-b6d9-768023486bb4

In [32]:
print(data.keys())

dict_keys(['2022-12-31/R1_D1_20221231.rsk', '2022-12-31/R1_D1_20221231.info', '2022-12-31/R1_D1_20221231.fmp', '2022-12-31/R1_D1_20221231.rtn', '2022-12-31/R1_D1_20221231.meta', '2022-12-31/R1_D1_20221231.cov', '2022-12-31/R1_D1_20221231.idm', '2022-12-31/R1_D1_20221231.exp'])

#### Factor Covariance Matrix (*.cov)

Factor covariance matrix provides ex-ante covariance based on the risk model estimation as of that point in time. The risk of a security or a portfolio can be estimated by combining the exposure with the covariance. The covariance values are annualized. The diagonal element is the estimation of volatility of the corresponding factor.

In [47]:
data['2022-12-31/R1_D1_20221231.cov'].head()

,Earnings Yld,EPS Growth (YoY),Momentum (12M-1M),Revision,Profitability,Volatility,Size (Mkt. Cap),Div Yield,Book to Market,Cash Flow Yield,...,Banks,Diversified Financials,Insurance,Software & Services,Technology Hardware & Equipment,Semiconductors & Semiconductor Equipment,Telecommunication Services,Media & Entertainment,Utilities,Real Estate
Earnings Yld,0.000866,-1.449807e-04,0.000079,0.000074,-6.120594e-04,-0.000024,0.000094,-0.000071,-0.000543,-0.000345,...,-0.001151,-0.000708,-0.000967,-0.000814,-0.000299,0.000387,-0.000743,-0.000717,-0.001211,-0.001205
EPS Growth (YoY),-0.000145,1.889733e-04,-0.000052,-0.000047,6.667153e-07,0.000068,-0.000006,0.000004,0.000017,0.000036,...,0.000241,0.000457,0.000340,0.000466,0.000191,0.000102,0.000336,0.000266,0.000279,0.000121
Momentum (12M-1M),0.000079,-5.229256e-05,0.002406,-0.000081,-9.464090e-05,0.000206,-0.000223,0.000374,0.000284,0.000978,...,0.001725,-0.001010,-0.000991,-0.002478,-0.000759,-0.002455,-0.002145,-0.000723,-0.003330,-0.000682
Revision,0.000074,-4.743015e-05,-0.000081,0.000331,-7.218557e-05,0.000128,-0.000023,-0.000027,-0.000012,0.000048,...,0.000283,0.000420,0.000441,0.000172,0.000440,0.000701,-0.000181,0.000296,0.000336,0.000495
Profitability,-0.000612,6.667153e-07,-0.000095,-0.000072,9.869264e-04,-0.000260,-0.000132,0.000061,0.000772,0.000143,...,0.000707,0.000044,0.000547,0.000098,-0.000039,-0.001045,0.000263,-0.000227,0.000746,0.000870

#### Factor Exposure Data (*.exp)

The file provides the factor exposure for each of the security in the risk universe.

In [46]:
data['2022-12-31/R1_D1_20221231.exp'].head()

,Earnings Yld,EPS Growth (YoY),Momentum (12M-1M),Revision,Profitability,Volatility,Size (Mkt. Cap),Div Yield,Book to Market,Cash Flow Yield,...,Banks,Diversified Financials,Insurance,Software & Services,Technology Hardware & Equipment,Semiconductors & Semiconductor Equipment,Telecommunication Services,Media & Entertainment,Utilities,Real Estate
ID,,,,,,,,,,,,,,,,,,,,,
K9RQE6VQGZ,-4.232164,2.630355,-0.805312,2.924837,-4.103194,1.425452,-2.524788,-0.903469,-3.521626,4.747996,...,0,0,0,0,0,0,0,0,0,0
04M5J6K6G4,-0.141731,-0.643752,0.369306,1.260209,-1.005601,-1.316804,-0.468940,0.752103,1.086648,0.923648,...,0,0,0,0,0,0,0,0,1,0
04M5JN8NG4,-0.726471,-0.270222,-1.112528,-0.356893,-0.642622,-0.750652,1.016936,0.344338,-0.446456,-0.981504,...,0,0,0,0,0,0,0,0,0,0
04M5O1EOK4,-0.346131,-2.184669,-0.831423,-1.487874,0.183510,1.270965,2.134824,-1.065790,0.553065,-1.102367,...,0,0,0,0,0,1,0,0,0,0
04M5YO72K4,-1.062421,1.183442,0.298969,1.506964,-0.045899,-0.734658,1.309863,0.551688,-1.085560,-1.266254,...,0,0,0,0,0,0,0,0,0,0

#### Security Idio Risk (*.rsk)

The idio risk provides a security specific risk. The units are percentage, hence it should be divided by 100 prior to adding to adding the risks of securities

In [50]:
data['2022-12-31/R1_D1_20221231.rsk'].head()

            Specific Risk
ID
K9RQE6VQGZ       0.259480
04M5J6K6G4       0.117224
04M5JN8NG4       0.179461
04M5O1EOK4       0.325641
04M5YO72K4       0.182426

#### Factor Returns File (*.rtn)

The factor returns provides percentage return. The returns are computed over the queried frequency. In order to compute decimal returns, the numbers should be divided by 100.

In [52]:

data['2022-12-31/R1_D1_20221231.rtn'].head()

                     Return
FactorName
Earnings Yld       0.790035
EPS Growth (YoY)   0.162028
Momentum (12M-1M) -0.398812
Revision          -0.078936
Profitability     -0.829157

#### Security Master (*.idm)

Basic security master file for each date listing reference information about the company

In [53]:
data['2022-12-31/R1_D1_20221231.idm'].head()

,SEDOL,TICKER,COMPANYNAME,QES_GSECTOR,QES_GGROUP,QES_COUNTRY,CURRENCY,IN_RISK_UNIV
ID,,,,,,,,
K9RQE6VQGZ,BCV7KT2,AAL,American Airlines Group Inc,Industrials,Transportation,US,USD,True
04M5J6K6G4,2048804,PNW,Pinnacle West Capital Corp,Utilities,Utilities,US,USD,True
04M5JN8NG4,2002305,ABT,Abbott Laboratories,Health Care,Health Care Equipment & Services,US,USD,True
04M5O1EOK4,2007849,AMD,Advanced Micro Devices Inc,Information Technology,Semiconductors & Semiconductor Equipment,US,USD,True
04M5YO72K4,2011602,APD,Air Products and Chemicals Inc.,Materials,Materials,US,USD,True

#### Factor Info File (*.info)

Provides details of each of the factor used in the risk model include the sector/country/currency when available.

In [54]:
data['2022-12-31/R1_D1_20221231.info'].head()

               Category        FactorAlias
FactorName
EPSYLD_LTM_B      Style       Earnings Yld
GR_INTR_EPS       Style   EPS Growth (YoY)
RTN_12M1M         Style  Momentum (12M-1M)
ES_EPS_NTM_R3M    Style           Revision
ROE               Style      Profitability

#### Factor Mimicking Portfolio (*.fmp)

File provides compositing of FMP as constructed for that date.

In [55]:
data['2022-12-31/R1_D1_20221231.fmp'].head()

,Earnings Yld,EPS Growth (YoY),Momentum (12M-1M),Revision,Profitability,Volatility,Size (Mkt. Cap),Div Yield,Book to Market,Cash Flow Yield,...,Banks,Diversified Financials,Insurance,Software & Services,Technology Hardware & Equipment,Semiconductors & Semiconductor Equipment,Telecommunication Services,Media & Entertainment,Utilities,Real Estate
ID,,,,,,,,,,,,,,,,,,,,,
K9RQE6VQGZ,0.013532,0.004061,-0.002955,0.002567,-0.028053,-0.000136,-0.001548,-0.000938,-0.031766,0.009081,...,0.011514,0.009058,-0.001069,0.000979,-0.000523,0.002672,0.003764,0.006670,-0.006511,-0.000043
04M5J6K6G4,0.000293,-0.003347,0.003711,0.004293,0.003897,0.002001,-0.005474,0.003954,0.004809,-0.002330,...,-0.006417,-0.002122,-0.004719,0.004276,0.000963,0.004541,-0.002997,0.001512,0.034090,-0.002507
04M5JN8NG4,0.002640,-0.001441,-0.005834,0.002288,0.000083,-0.001928,0.003873,0.001377,-0.000013,-0.000868,...,-0.004832,-0.003673,0.001818,-0.002020,-0.001865,-0.001431,-0.008332,-0.001518,-0.000442,-0.002825
04M5O1EOK4,-0.002245,-0.001173,-0.000935,-0.001228,0.001482,0.000318,0.001341,-0.002014,0.002644,0.000214,...,0.000719,-0.000963,0.000831,-0.001751,-0.000257,0.024731,0.001330,-0.003321,0.002654,0.002075
04M5YO72K4,-0.000362,-0.000879,0.000654,0.001476,-0.001809,-0.001580,0.001551,0.000358,-0.001584,-0.002344,...,0.002641,-0.000232,-0.002146,-0.002818,0.000532,0.002195,0.002508,0.002336,-0.001385,-0.000788