### Interaction with Jupyter Notebook remotely

The notebook does the following

- Connects to user jupyter session using the token
- Queries notebook content in the server
- Queries running kernels
- Executes code on jupyter kernel
- Downloads data

### Create a new object to communicate with the server

In [57]:
from jupyterhub_client import  RemoteJupyterClient
remote = RemoteJupyterClient('<username here>','<token here>','<url here>')

### Lists down running kernels. At least one kernel should be available to execute the code

In [51]:
remote.kernels()

,id,name,last_activity,execution_state,connections
0,12263c47-20c1-4311-b93a-bf79911e8042,python3,2022-03-24T17:43:37.541988Z,idle,1

### Read content of a notebook

In [52]:
notebook = remote.content('projects/demo/jupyter-remote/Remote Jupyter Demo.ipynb')

In [53]:
notebook

,cell_type,execution_count,metadata,outputs,source
0,code,31.0,"{'scrolled': True, 'trusted': True}","[{'name': 'stderr', 'output_type': 'stream', '...",from lquantPy import LQuant\nwq = LQuant.LQuant()
1,code,28.0,{'trusted': True},"[{'name': 'stdout', 'output_type': 'stream', '...","sdfdfdsfdfdfdf\n\nprint(""Fetching Data...."")\n..."
2,code,NaN,{'trusted': True},[],
3,code,6.0,{'trusted': True},"[{'name': 'stderr', 'output_type': 'stream', '...",

### Execute Remote Code on the server

In [58]:
response = remote.execute('12263c47-20c1-4311-b93a-bf79911e8042', notebook.loc[1,'source'])

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-46-adca94e4ad10> in <module>()
----> 1 sdfdfdsfdfdfdf
      2
      3 print("Fetching Data....")
      4 r1 = wq.new_request().runFor('SP500').start('2022-01-31').to('2022-02-28').at('1me').a('PRCCD').addInFlag()
      5 data1 = wq.get_data(r1)

NameError: name 'sdfdfdsfdfdfdf' is not defined

### Download Data from the server

In [16]:
remote.content('projects/demo/jupyter-remote')

,name,path,last_modified,created,content,format,mimetype,size,writable,type
0,lquant.log,projects/demo/jupyter-remote/lquant.log,2022-03-24T17:14:12.724552Z,2022-03-24T17:14:12.724552Z,None,None,None,160750,True,file
1,lquant-error.log,projects/demo/jupyter-remote/lquant-error.log,2022-03-23T18:38:17.828686Z,2022-03-23T18:38:17.828686Z,None,None,None,0,True,file
2,sp500.csv,projects/demo/jupyter-remote/sp500.csv,2022-03-24T17:14:12.752547Z,2022-03-24T17:14:12.752547Z,None,None,text/csv,35886,True,file
3,Remote Jupyter Demo.ipynb,projects/demo/jupyter-remote/Remote Jupyter De...,2022-03-24T12:39:27.463091Z,2022-03-24T12:39:27.463091Z,None,None,None,3605,True,notebook